version: '3.9'

services:
  postgres:
    image: postgres:17.0
    environment:
      POSTGRES_DB: main_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pwd
      PGDATA: /data/postgres
    healthcheck:
      test: "pg_isready -h localhost -p 5432 -q -U postgres"
      interval: 30s
      timeout: 10s
      retries: 5      
    volumes:
       - dbpostgres:/data/main-db
    ports:
      - "5432:5432"
    restart: unless-stopped


volumes:
    dbpostgres:
      external: true